image: docker:latest

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - docker build -t registry.gitlab.com/liapractise/snacks-react:1.0.0 .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push registry.gitlab.com/liapractise/snacks-react:1.0.0

deploy:
  stage: deploy
  image: docker:stable
  services:
    - "docker:dind"
  variables:  # not strictly needed, depending on runner configuration
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_TLS_CERTDIR: ""
    script:
      - docker pull registry.gitlab.com/liapractise/snacks-react:1.0.0
      - docker run -p 80:80 registry.gitlab.com/liapractise/snacks-react:1.0.0
  #    - docker run --privileged -p 80:80 registry.gitlab.com/liapractise/snacks-react:1.0.0
