image: docker:20.10.16

stages:
  - build
  - deploy

before_script:
  - docker info

build:
  stage: build
  script:
    - docker build -t registry.gitlab.com/liapractise/snacks:jdk-17-slim .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push registry.gitlab.com/liapractise/snacks:jdk-17-slim

deploy:
  stage: deploy
  image: docker:19.03.0
  services:
    - docker:20.10.16-dind
  script:
    - docker pull registry.gitlab.com/liapractise/snacks:jdk-17-slim
    - docker run --privileged -d -p 80:80 registry.gitlab.com/liapractise/snacks:jdk-17-slim

