version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: snackscont
    ports:
      - "8080:8080"
#    environment: # use application.properties instead
#      - SPRING_DATA_MONGODB_HOST=db
#      - SPRING_DATA_MONGODB_DATABASE=snackscomposedb
#      - SPRING_DATA_MONGODB_PORT=27017
    depends_on:
      - db

  db:
    image: mongo:5.0.14
    container_name: mongocont
    ports:
      - "27017:27017"
    volumes:
      - C:/data/contdata:/data/db
