version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: snackscont
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: mongo:5.0.14
    container_name: mongocont
    ports:
      - "27017:27017"
    volumes:
      - C:/data/contdata:/data/db
